"""add_remind_to

Revision ID: 6ea91430d962
Revises: 735adb1a5798
Create Date: 2024-04-22 05:33:53.164825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea91430d962'
down_revision: Union[str, None] = '735adb1a5798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remind_target', sa.Column('remind_to', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remind_target', 'remind_to')
    # ### end Alembic commands ###
