"""add_remind_msg_id_col

Revision ID: b9600955910f
Revises: f58755a6d46c
Create Date: 2024-05-10 10:13:11.640585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9600955910f'
down_revision: Union[str, None] = 'f58755a6d46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remind_target', sa.Column('remind_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remind_target', 'remind_message_id')
    # ### end Alembic commands ###
